### ISSUE TITLE
MongoDB guide sample application broken

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-guides#1266]
The MongoDB guide doesn't have the test resources plugin added and configured correctly so tests fail out of the box.

## Steps to reproduce

1. Download https://guides.micronaut.io/latest/micronaut-data-mongodb-asynchronous-gradle-java.html
2. Run tests (broken)
3. Add `id("io.micronaut.test-resources") version "3.7.8"` to build
4. Run tests (still broken with Read Timeout exception)
5. Add 

```yaml
micronaut:
  application:
    name: micronautguide
  http:
    client:
      read-timeout: 10s
```

and

```groovy
micronaut {
   ...
    testResources {
        clientTimeout = 360
    }
}

```

Now passing.
