### ISSUE TITLE
HttpClient guide fails with JDK Http Client

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-guides#1276]
## Steps to produce

Clone branch `sdelamo-patch-3`
Edit `guides/micronaut-http-client/metadata.json`
Replace `http-client` with `http-client-jdk`
Execute `./gradlew clean micronautHttpClientBuild --rerun-tasks --no-build-cache`

```
Caused by: io.micronaut.serde.exceptions.SerdeException: Unexpected token START_OBJECT, expected START_ARRAY 
```

**Comment by timyates** [comment]
So the `GithubDeclarativeControllerTest` fails as we don't have a Streaming Client for the JDK HttpClient

**Comment by timyates** [comment]
I believe the error in the description is cause by the client not picking up the config from

```
micronaut:
  http:
    services:
      github:
        url: 'https://api.github.com'
```

for some reason 🤔 investigating
