### ISSUE TITLE
GraphQL ToDo App should have non-default DB initialization timeout

### ISSUE THREAD

**Issue by eeverman** [micronaut-projects/micronaut-guides#1287]
The [DB configuration](https://github.com/micronaut-projects/micronaut-guides/blob/4da0fea5f733cc8ada2d94871441bf29ed64c257/guides/micronaut-graphql-todo/src/main/resources/application.yml#L8) for the micronaut-graphql-todo app has no `initialization-fail-timeout` set.  The default for that is 1ms, so if your machine happens to be a bit busy or slow, the app fails to start with a DB connection error.  Adding `initialization-fail-timeout: 20000` (20 seconds) would fix this for all but the slowest machines.

So that section would look like this:
```yaml
#tag::datasource[]
datasources:
  default:
    driverClassName: org.postgresql.Driver  # <2>
    dialect: POSTGRES # <3>
    schema-generate: NONE # <4>
    initialization-fail-timeout: 20000
#end::datasource[]
```
