### ISSUE TITLE
Clarifying Text In Autonomous DB Guide

### ISSUE THREAD

**Issue by jeffscottbrown** [micronaut-projects/micronaut-guides#267]
The text at https://github.com/micronaut-projects/micronaut-guides/blob/224cf26ffaeefaa7c147f7a7b95cbc6374883a4c/guides/micronaut-oracle-autonomous-db/micronaut-oracle-autonomous-db.adoc for https://guides.micronaut.io/latest/micronaut-oracle-autonomous-db-gradle-java.html says the following:

> Replace the generated application-test.yml with this:

I don't think `application-test.yml` has been generated to that point.

**Comment by burtbeckwith** [comment]
run `mn create-app example.micronaut.micronautguide --build=gradle --lang=java --jdk=11 --features=oracle,data-jdbc,oracle-cloud-sdk,flyway,testcontainers` (or one of the other variants from the guide) and you'll see 

```
datasources:
  default:
    url: jdbc:tc:oracle:thin:@/xe
    driverClassName: org.testcontainers.jdbc.ContainerDatabaseDriver
```

in src/test/resources/application-test.yml
